import {
  Braces,
  Key,
  Code,
  Link,
  Terminal,
  Clock,
  Search,
  GitCompare,
  Hash,
  Fingerprint,
  Lock,
  Palette,
  Layers,
  FileText,
  Type,
  List,
  Binary,
  Globe,
  Shield,
  Calculator,
  Ruler,
  FileJson,
  FileCode,
  QrCode,
  BarChart3,
  Calendar,
  TypeIcon,
  FileDigit,
  Network,
  Database,
  Zap,
  Camera,
  Video,
  Image,
  Maximize2,
  Minimize2,
  Maximize,
  Minimize,
  LucideIcon,
} from "lucide-react";

export interface Tool {
  id: string;
  name: string;
  description: string;
  category: "json" | "web" | "dev" | "frontend" | "productivity" | "security" | "converter";
  path: string;
  icon: LucideIcon;
  popular?: boolean;
  new?: boolean;
}

export const tools: Tool[] = [
  // JSON Tools
  {
    id: "json-formatter",
    name: "JSON Formatter",
    description: "Format, validate, and beautify JSON data with syntax highlighting",
    category: "json",
    path: "/json-formatter",
    icon: Braces,
    popular: true,
  },
  {
    id: "json-to-ts",
    name: "JSON to TypeScript",
    description: "Convert JSON objects to TypeScript interfaces",
    category: "json",
    path: "/json-to-ts",
    icon: FileJson,
    new: true,
  },
  
  // Web & API Tools
  {
    id: "jwt-decoder",
    name: "JWT Decoder",
    description: "Decode and inspect JWT tokens to view header and payload",
    category: "web",
    path: "/jwt-decoder",
    icon: Key,
    popular: true,
  },
  {
    id: "base64",
    name: "Base64 Encoder/Decoder",
    description: "Encode and decode Base64 strings with Unicode support",
    category: "web",
    path: "/base64",
    icon: Binary,
  },
  {
    id: "url-encoder",
    name: "URL Encoder/Decoder",
    description: "Encode and decode URL parameters and full URLs",
    category: "web",
    path: "/url-encoder",
    icon: Link,
  },
  {
    id: "html-encoder",
    name: "HTML Encoder/Decoder",
    description: "Encode and decode HTML entities",
    category: "web",
    path: "/html-encoder",
    icon: Code,
    new: true,
  },
  {
    id: "curl-converter",
    name: "Curl Converter",
    description: "Convert curl commands to JavaScript fetch or axios code",
    category: "web",
    path: "/curl-converter",
    icon: Terminal,
  },
  
  // Developer Utilities
  {
    id: "timestamp",
    name: "Timestamp Converter",
    description: "Convert between Unix timestamps and human-readable dates",
    category: "dev",
    path: "/timestamp",
    icon: Clock,
    popular: true,
  },
  {
    id: "regex-tester",
    name: "Regex Tester",
    description: "Test regular expressions with live matching and capture groups",
    category: "dev",
    path: "/regex-tester",
    icon: Search,
    popular: true,
  },
  {
    id: "diff-checker",
    name: "Diff Checker",
    description: "Compare two texts and find differences with highlighting",
    category: "dev",
    path: "/diff-checker",
    icon: GitCompare,
  },
  {
    id: "hash-generator",
    name: "Hash Generator",
    description: "Generate MD5, SHA1, SHA256 hashes from text",
    category: "dev",
    path: "/hash-generator",
    icon: Hash,
  },
  {
    id: "uuid-generator",
    name: "UUID Generator",
    description: "Generate random UUIDs/GUIDs with multiple format options",
    category: "dev",
    path: "/uuid-generator",
    icon: Fingerprint,
  },
  {
    id: "password-generator",
    name: "Password Generator",
    description: "Generate secure random passwords with customizable options",
    category: "dev",
    path: "/password-generator",
    icon: Lock,
    popular: true,
  },
  {
    id: "cron-parser",
    name: "Cron Parser",
    description: "Parse and explain cron expressions in plain English",
    category: "dev",
    path: "/cron-parser",
    icon: Calendar,
    new: true,
  },
  {
    id: "sql-formatter",
    name: "SQL Formatter",
    description: "Format and beautify SQL queries",
    category: "dev",
    path: "/sql-formatter",
    icon: Database,
    new: true,
  },
  
  // Frontend Tools
  {
    id: "color-picker",
    name: "Color Picker",
    description: "Pick colors and generate palettes with HEX, RGB, HSL values",
    category: "frontend",
    path: "/color-picker",
    icon: Palette,
    popular: true,
  },
  {
    id: "gradient-generator",
    name: "Gradient Generator",
    description: "Create beautiful CSS gradients with multiple color stops",
    category: "frontend",
    path: "/gradient-generator",
    icon: Layers,
  },
  {
    id: "css-minifier",
    name: "CSS Minifier",
    description: "Minify CSS code by removing whitespace and comments",
    category: "frontend",
    path: "/css-minifier",
    icon: FileCode,
    new: true,
  },
  {
    id: "js-minifier",
    name: "JS Minifier",
    description: "Minify JavaScript code for production",
    category: "frontend",
    path: "/js-minifier",
    icon: FileDigit,
    new: true,
  },
  
  // Productivity
  {
    id: "markdown-previewer",
    name: "Markdown Previewer",
    description: "Live preview Markdown with rendered HTML output",
    category: "productivity",
    path: "/markdown-previewer",
    icon: FileText,
  },
  {
    id: "case-converter",
    name: "Case Converter",
    description: "Convert between camelCase, PascalCase, snake_case, kebab-case",
    category: "productivity",
    path: "/case-converter",
    icon: Type,
  },
  {
    id: "text-sorter",
    name: "Text Sorter",
    description: "Sort lines, remove duplicates, and clean up text",
    category: "productivity",
    path: "/text-sorter",
    icon: List,
  },
  {
    id: "lorem-ipsum",
    name: "Lorem Ipsum Generator",
    description: "Generate placeholder text for your designs",
    category: "productivity",
    path: "/lorem-ipsum",
    icon: TypeIcon,
    new: true,
  },
  
  // Security
  {
    id: "qr-generator",
    name: "QR Code Generator",
    description: "Generate QR codes for URLs and text",
    category: "security",
    path: "/qr-generator",
    icon: QrCode,
    new: true,
  },
];

export const categories = [
  { 
    id: "json", 
    name: "JSON Tools", 
    color: "bg-blue-500",
    bgColor: "bg-blue-500/20",
    gradient: "from-blue-500 to-cyan-500",
    badgeColor: "bg-blue-500/20 text-blue-400",
    icon: Braces,
  },
  { 
    id: "web", 
    name: "Web & API", 
    color: "bg-green-500",
    bgColor: "bg-green-500/20",
    gradient: "from-green-500 to-emerald-500",
    badgeColor: "bg-green-500/20 text-green-400",
    icon: Globe,
  },
  { 
    id: "dev", 
    name: "Dev Utilities", 
    color: "bg-yellow-500",
    bgColor: "bg-yellow-500/20",
    gradient: "from-yellow-500 to-orange-500",
    badgeColor: "bg-yellow-500/20 text-yellow-400",
    icon: Terminal,
  },
  { 
    id: "frontend", 
    name: "Frontend", 
    color: "bg-purple-500",
    bgColor: "bg-purple-500/20",
    gradient: "from-purple-500 to-pink-500",
    badgeColor: "bg-purple-500/20 text-purple-400",
    icon: Palette,
  },
  { 
    id: "productivity", 
    name: "Productivity", 
    color: "bg-red-500",
    bgColor: "bg-red-500/20",
    gradient: "from-red-500 to-rose-500",
    badgeColor: "bg-red-500/20 text-red-400",
    icon: Zap,
  },
  { 
    id: "security", 
    name: "Security", 
    color: "bg-cyan-500",
    bgColor: "bg-cyan-500/20",
    gradient: "from-cyan-500 to-teal-500",
    badgeColor: "bg-cyan-500/20 text-cyan-400",
    icon: Shield,
  },
] as const;
