export interface Tool {
  id: string;
  name: string;
  description: string;
  category: "json" | "web" | "dev" | "frontend" | "productivity" | "security" | "converter";
  path: string;
  icon: string;
  popular?: boolean;
  new?: boolean;
}

export const tools: Tool[] = [
  // JSON Tools
  {
    id: "json-formatter",
    name: "JSON Formatter",
    description: "Format, validate, and beautify JSON data with syntax highlighting, minify, sort keys, and export to multiple programming languages",
    category: "json",
    path: "/json-formatter",
    icon: "Braces",
    popular: true,
  },
  {
    id: "json-to-ts",
    name: "JSON to TypeScript",
    description: "Convert JSON objects to TypeScript interfaces with type inference",
    category: "json",
    path: "/json-to-ts",
    icon: "FileCode",
    new: true,
  },
  {
    id: "json-to-csv",
    name: "JSON to CSV",
    description: "Convert JSON arrays to CSV format with customizable options",
    category: "json",
    path: "/json-to-csv",
    icon: "FileSpreadsheet",
    new: true,
  },
  {
    id: "csv-json",
    name: "CSV / JSON Converter",
    description: "Convert between CSV and JSON formats with customizable options",
    category: "json",
    path: "/csv-json",
    icon: "FileSpreadsheet",
    new: true,
  },
  
  // Web & API Tools
  {
    id: "base32",
    name: "Base32 Converter",
    description: "Encode and decode Base32 strings",
    category: "web",
    path: "/base32",
    icon: "Binary",
    new: true,
  },
  {
    id: "hex-converter",
    name: "Hex Converter",
    description: "Convert text to hexadecimal and vice versa",
    category: "web",
    path: "/hex-converter",
    icon: "Hexagon",
    new: true,
  },
  {
    id: "yaml-converter",
    name: "YAML Converter",
    description: "Convert between YAML and JSON formats with validation",
    category: "web",
    path: "/yaml-converter",
    icon: "FileCode",
    new: true,
  },
  {
    id: "jwt-decoder",
    name: "JWT Decoder",
    description: "Decode and inspect JWT tokens with claims validation, sample tokens, and multi-token support",
    category: "web",
    path: "/jwt-decoder",
    icon: "Key",
    popular: true,
  },
  {
    id: "base64",
    name: "Base64 Encoder/Decoder",
    description: "Encode and decode Base64 with URL-safe mode, batch processing, file upload, and image preview",
    category: "web",
    path: "/base64",
    icon: "Binary",
  },
  {
    id: "url-encoder",
    name: "URL Encoder/Decoder",
    description: "Encode and decode URL parameters and full URLs",
    category: "web",
    path: "/url-encoder",
    icon: "Link",
  },
  {
    id: "html-encoder",
    name: "HTML Encoder/Decoder",
    description: "Encode and decode HTML entities",
    category: "web",
    path: "/html-encoder",
    icon: "Code",
    new: true,
  },
  {
    id: "curl-converter",
    name: "Curl Converter",
    description: "Convert curl commands to JavaScript fetch or axios code",
    category: "web",
    path: "/curl-converter",
    icon: "Terminal",
  },
  {
    id: "xml-formatter",
    name: "XML Formatter",
    description: "Format and validate XML with proper indentation",
    category: "web",
    path: "/xml-formatter",
    icon: "Code",
    new: true,
  },
  {
    id: "user-agent-parser",
    name: "User Agent Parser",
    description: "Parse User-Agent strings to extract browser, OS, and device information",
    category: "web",
    path: "/user-agent-parser",
    icon: "User",
    new: true,
  },
  {
    id: "http-status-codes",
    name: "HTTP Status Codes",
    description: "Reference for all HTTP status codes with search and filtering",
    category: "web",
    path: "/http-status-codes",
    icon: "Globe",
    new: true,
  },
  {
    id: "csv-table",
    name: "CSV to Table",
    description: "Convert CSV data to HTML tables with live preview",
    category: "web",
    path: "/csv-table",
    icon: "Table",
    new: true,
  },
  
  // Developer Utilities
  {
    id: "number-base",
    name: "Number Base Converter",
    description: "Convert between decimal, binary, hexadecimal, and octal",
    category: "dev",
    path: "/number-base",
    icon: "Calculator",
    new: true,
  },
  {
    id: "sql-formatter",
    name: "SQL Formatter",
    description: "Format and beautify SQL queries with proper indentation and syntax highlighting",
    category: "dev",
    path: "/sql-formatter",
    icon: "Database",
    new: true,
  },
  {
    id: "cron-parser",
    name: "Cron Parser",
    description: "Parse cron expressions and see the next execution times",
    category: "dev",
    path: "/cron-parser",
    icon: "Clock",
    new: true,
  },
  {
    id: "cron-generator",
    name: "Cron Generator",
    description: "Interactive cron expression builder with visual controls and next run preview",
    category: "dev",
    path: "/cron-generator",
    icon: "Clock",
    new: true,
  },
  {
    id: "timestamp",
    name: "Timestamp Converter",
    description: "Convert between Unix timestamps with timezone support, duration calculator, and natural language parsing",
    category: "dev",
    path: "/timestamp",
    icon: "Clock",
    popular: true,
  },
  {
    id: "regex-tester",
    name: "Regex Tester",
    description: "Test regular expressions with live matching, saved patterns, library, replace functionality, and cheat sheet",
    category: "dev",
    path: "/regex-tester",
    icon: "Search",
    popular: true,
  },
  {
    id: "diff-checker",
    name: "Diff Checker",
    description: "Compare two texts and find differences with highlighting",
    category: "dev",
    path: "/diff-checker",
    icon: "GitCompare",
  },
  {
    id: "hash-generator",
    name: "Hash Generator",
    description: "Generate MD5, SHA1, SHA256, SHA512 hashes with file support, HMAC generation, and hash comparison",
    category: "dev",
    path: "/hash-generator",
    icon: "Hash",
  },
  {
    id: "uuid-generator",
    name: "UUID Generator",
    description: "Generate random UUIDs/GUIDs with multiple format options",
    category: "dev",
    path: "/uuid-generator",
    icon: "Fingerprint",
  },
  {
    id: "password-generator",
    name: "Password Generator",
    description: "Generate secure passwords with passphrases, PINs, pronounceable options, strength meter, and settings memory",
    category: "dev",
    path: "/password-generator",
    icon: "Lock",
    popular: true,
  },
  
  // Frontend Tools
  {
    id: "css-grid-generator",
    name: "CSS Grid Generator",
    description: "Visual CSS grid layout builder with interactive controls",
    category: "frontend",
    path: "/css-grid-generator",
    icon: "Grid",
    new: true,
  },
  {
    id: "box-shadow-generator",
    name: "Box Shadow Generator",
    description: "Create beautiful CSS box shadows with visual controls",
    category: "frontend",
    path: "/box-shadow-generator",
    icon: "Square",
    new: true,
  },
  {
    id: "svg-to-jsx",
    name: "SVG to JSX Converter",
    description: "Convert SVG code to React JSX components",
    category: "frontend",
    path: "/svg-to-jsx",
    icon: "Code",
    new: true,
  },
  {
    id: "color-picker",
    name: "Color Picker",
    description: "Pick colors with color harmony generators, palette export, WCAG contrast checker, and history",
    category: "frontend",
    path: "/color-picker",
    icon: "Palette",
    popular: true,
  },
  {
    id: "gradient-generator",
    name: "Gradient Generator",
    description: "Create beautiful CSS gradients with multiple color stops",
    category: "frontend",
    path: "/gradient-generator",
    icon: "Layers",
  },
  
  // Productivity
  {
    id: "markdown-previewer",
    name: "Markdown Previewer",
    description: "Live preview Markdown with rendered HTML output",
    category: "productivity",
    path: "/markdown-previewer",
    icon: "FileText",
  },
  {
    id: "case-converter",
    name: "Case Converter",
    description: "Convert between camelCase, PascalCase, snake_case, kebab-case",
    category: "productivity",
    path: "/case-converter",
    icon: "Type",
  },
  {
    id: "case-tester",
    name: "Text Case Tester",
    description: "Test text against different case formats and detect case types",
    category: "productivity",
    path: "/case-tester",
    icon: "Type",
    new: true,
  },
  {
    id: "text-sorter",
    name: "Text Sorter",
    description: "Sort lines, remove duplicates, and clean up text",
    category: "productivity",
    path: "/text-sorter",
    icon: "List",
  },
  {
    id: "lorem-ipsum",
    name: "Lorem Ipsum Generator",
    description: "Generate placeholder text for your designs",
    category: "productivity",
    path: "/lorem-ipsum",
    icon: "Type",
    new: true,
  },
  
  // Security
  {
    id: "hmac-generator",
    name: "HMAC Generator",
    description: "Generate HMAC signatures with MD5, SHA1, SHA256, SHA512",
    category: "security",
    path: "/hmac-generator",
    icon: "Shield",
    new: true,
  },
  {
    id: "bcrypt-generator",
    name: "BCrypt Hash Generator",
    description: "Generate BCrypt hashes for password storage",
    category: "security",
    path: "/bcrypt-generator",
    icon: "Lock",
    new: true,
  },
  {
    id: "qr-generator",
    name: "QR Code Generator",
    description: "Generate QR codes for URLs and text",
    category: "security",
    path: "/qr-generator",
    icon: "QrCode",
    new: true,
  },
  
  // New JSON Tools
  {
    id: "json-path",
    name: "JSONPath Tester",
    description: "Test JSONPath expressions against JSON data with visual results",
    category: "json",
    path: "/json-path",
    icon: "Search",
    new: true,
  },
  {
    id: "json-schema",
    name: "JSON Schema Validator",
    description: "Validate JSON against a JSON Schema with detailed error reporting",
    category: "json",
    path: "/json-schema",
    icon: "FileCheck",
    new: true,
  },
  
  // New Web Tools
  {
    id: "url-shortener",
    name: "URL Shortener",
    description: "Encode URLs to Base62 short codes and decode them back",
    category: "web",
    path: "/url-shortener",
    icon: "Link",
    new: true,
  },
  {
    id: "base64-image",
    name: "Base64 Image Converter",
    description: "Convert images to Base64 and vice versa with preview",
    category: "web",
    path: "/base64-image",
    icon: "Image",
    new: true,
  },
  {
    id: "unicode-picker",
    name: "Unicode Character Picker",
    description: "Browse and copy Unicode characters, emojis, and symbols",
    category: "web",
    path: "/unicode-picker",
    icon: "Type",
    new: true,
  },
  
  // New Security Tools
  {
    id: "jwt-generator",
    name: "JWT Token Generator",
    description: "Create and sign JWT tokens with custom claims and algorithms",
    category: "security",
    path: "/jwt-generator",
    icon: "Key",
    new: true,
  },
  
  // New Dev Tools
  {
    id: "text-diff",
    name: "Text Diff Viewer",
    description: "Compare two texts and see differences side-by-side or unified",
    category: "dev",
    path: "/text-diff",
    icon: "GitCompare",
    new: true,
  },
];

export const categories = [
  { 
    id: "json", 
    name: "JSON Tools", 
    color: "bg-blue-500",
    bgColor: "bg-blue-500/20",
    gradient: "from-blue-500 to-cyan-500",
    badgeColor: "bg-blue-500/20 text-blue-400",
    icon: "Braces",
  },
  { 
    id: "web", 
    name: "Web & API", 
    color: "bg-green-500",
    bgColor: "bg-green-500/20",
    gradient: "from-green-500 to-emerald-500",
    badgeColor: "bg-green-500/20 text-green-400",
    icon: "Globe",
  },
  { 
    id: "dev", 
    name: "Dev Utilities", 
    color: "bg-yellow-500",
    bgColor: "bg-yellow-500/20",
    gradient: "from-yellow-500 to-orange-500",
    badgeColor: "bg-yellow-500/20 text-yellow-400",
    icon: "Terminal",
  },
  { 
    id: "frontend", 
    name: "Frontend", 
    color: "bg-purple-500",
    bgColor: "bg-purple-500/20",
    gradient: "from-purple-500 to-pink-500",
    badgeColor: "bg-purple-500/20 text-purple-400",
    icon: "Palette",
  },
  { 
    id: "productivity", 
    name: "Productivity", 
    color: "bg-red-500",
    bgColor: "bg-red-500/20",
    gradient: "from-red-500 to-rose-500",
    badgeColor: "bg-red-500/20 text-red-400",
    icon: "Zap",
  },
  { 
    id: "security", 
    name: "Security", 
    color: "bg-cyan-500",
    bgColor: "bg-cyan-500/20",
    gradient: "from-cyan-500 to-teal-500",
    badgeColor: "bg-cyan-500/20 text-cyan-400",
    icon: "Shield",
  },
] as const;
