import {
  Braces,
  Key,
  Code,
  Link,
  Terminal,
  Clock,
  Search,
  GitCompare,
  Hash,
  Fingerprint,
  Lock,
  Palette,
  Layers,
  FileText,
  Type,
  List,
  Binary,
  Globe,
  Shield,
  Calculator,
  Ruler,
  FileJson,
  FileCode,
  QrCode,
  BarChart3,
  Calendar,
  TypeIcon,
  FileDigit,
  Network,
  Database,
  Zap,
} from "lucide-react";
import { LucideIcon } from "lucide-react";

export interface Tool {
  id: string;
  name: string;
  description: string;
  category: "json" | "web" | "dev" | "frontend" | "productivity" | "security" | "converter";
  path: string;
  icon: LucideIcon;
  popular?: boolean;
  new?: boolean;
}

export const tools: Tool[] = [
  // JSON Tools
  {
    id: "json-formatter",
    name: "JSON Formatter",
    description: "Format, validate, and beautify JSON data with syntax highlighting",
    category: "json",
    path: "/json-formatter",
    icon: Braces,
    popular: true,
  },
  {
    id: "json-to-csv",
    name: "JSON to CSV",
    description: "Convert JSON data to CSV format",
    category: "json",
    path: "/json-to-csv",
    icon: FileJson,
    new: true,
  },
  {
    id: "json-to-yaml",
    name: "JSON to YAML",
    description: "Convert JSON to YAML and vice versa",
    category: "json",
    path: "/json-to-yaml",
    icon: FileCode,
    new: true,
  },

  // Web & API Tools
  {
    id: "jwt-decoder",
    name: "JWT Decoder",
    description: "Decode and inspect JWT tokens with payload analysis",
    category: "web",
    path: "/jwt-decoder",
    icon: Key,
    popular: true,
  },
  {
    id: "base64",
    name: "Base64 Encoder/Decoder",
    description: "Encode and decode Base64 strings with Unicode support",
    category: "web",
    path: "/base64",
    icon: Binary,
    popular: true,
  },
  {
    id: "url-encoder",
    name: "URL Encoder/Decoder",
    description: "Encode and decode URL parameters and full URLs",
    category: "web",
    path: "/url-encoder",
    icon: Globe,
  },
  {
    id: "curl-converter",
    name: "Curl Converter",
    description: "Convert curl commands to fetch, axios, or other formats",
    category: "web",
    path: "/curl-converter",
    icon: Terminal,
  },
  {
    id: "html-encoder",
    name: "HTML Encoder/Decoder",
    description: "Encode and decode HTML entities",
    category: "web",
    path: "/html-encoder",
    icon: Code,
    new: true,
  },
  {
    id: "qr-generator",
    name: "QR Code Generator",
    description: "Generate QR codes from text or URLs",
    category: "web",
    path: "/qr-generator",
    icon: QrCode,
    new: true,
  },

  // Dev Utilities
  {
    id: "timestamp",
    name: "Timestamp Converter",
    description: "Convert between Unix timestamps and human-readable dates",
    category: "dev",
    path: "/timestamp",
    icon: Clock,
    popular: true,
  },
  {
    id: "regex-tester",
    name: "Regex Tester",
    description: "Test regular expressions with live matching and capture groups",
    category: "dev",
    path: "/regex-tester",
    icon: Search,
    popular: true,
  },
  {
    id: "diff-checker",
    name: "Diff Checker",
    description: "Compare two texts and find differences with syntax highlighting",
    category: "dev",
    path: "/diff-checker",
    icon: GitCompare,
  },
  {
    id: "hash-generator",
    name: "Hash Generator",
    description: "Generate MD5, SHA1, SHA256, and SHA512 hashes",
    category: "dev",
    path: "/hash-generator",
    icon: Hash,
  },
  {
    id: "uuid-generator",
    name: "UUID Generator",
    description: "Generate random UUIDs/GUIDs in various formats",
    category: "dev",
    path: "/uuid-generator",
    icon: Fingerprint,
  },
  {
    id: "password-generator",
    name: "Password Generator",
    description: "Generate secure random passwords with custom rules",
    category: "dev",
    path: "/password-generator",
    icon: Lock,
    popular: true,
  },
  {
    id: "lorem-ipsum",
    name: "Lorem Ipsum Generator",
    description: "Generate placeholder text for designs",
    category: "dev",
    path: "/lorem-ipsum",
    icon: TypeIcon,
    new: true,
  },
  {
    id: "cron-parser",
    name: "Cron Parser",
    description: "Parse and explain cron expressions",
    category: "dev",
    path: "/cron-parser",
    icon: Calendar,
    new: true,
  },

  // Security Tools
  {
    id: "password-strength",
    name: "Password Strength Checker",
    description: "Check password strength and estimate crack time",
    category: "security",
    path: "/password-strength",
    icon: Shield,
    new: true,
  },

  // Converters
  {
    id: "number-base",
    name: "Number Base Converter",
    description: 'Encode and decode URL parameters and full URLs',
    category: 'web',
    path: '/url-encoder',
    icon: Link,
    color: 'from-emerald-600 to-cyan-500',
  },
  {
    id: 'curl-converter',
    name: 'Curl Converter',
    description: 'Convert curl commands to fetch, axios, or other HTTP clients',
    category: 'web',
    path: '/curl-converter',
    icon: Terminal,
    color: 'from-emerald-500 to-blue-500',
  },
  {
    id: 'html-encoder',
    name: 'HTML Encoder',
    description: 'Encode special characters to HTML entities',
    category: 'web',
    path: '/html-encoder',
    icon: Code,
    color: 'from-green-500 to-emerald-500',
  },
  
  // Dev Utilities
  {
    id: 'timestamp',
    name: 'Timestamp Converter',
    description: 'Convert between Unix timestamps and human-readable dates',
    category: 'dev',
    path: '/timestamp',
    icon: Clock,
    badge: 'Popular',
    color: 'from-amber-500 to-orange-500',
  },
  {
    id: 'regex-tester',
    name: 'Regex Tester',
    description: 'Test regular expressions with live matching and capture groups',
    category: 'dev',
    path: '/regex-tester',
    icon: Search,
    color: 'from-amber-400 to-yellow-500',
  },
  {
    id: 'diff-checker',
    name: 'Diff Checker',
    description: 'Compare two texts and visualize differences side by side',
    category: 'dev',
    path: '/diff-checker',
    icon: GitCompare,
    color: 'from-orange-500 to-red-500',
  },
  {
    id: 'hash-generator',
    name: 'Hash Generator',
    description: 'Generate MD5, SHA1, SHA256, SHA512 hashes',
    category: 'dev',
    path: '/hash-generator',
    icon: Hash,
    color: 'from-amber-500 to-pink-500',
  },
  {
    id: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Generate random UUIDs/GUIDs in various formats',
    category: 'dev',
    path: '/uuid-generator',
    icon: Fingerprint,
    color: 'from-yellow-500 to-amber-500',
  },
  {
    id: 'password-generator',
    name: 'Password Generator',
  ListFilter,
  ListRestart,
  ListX,
  GripVertical,
  GripHorizontal,
  Hand,
  HandMetal,
  Pointer,
  Crosshair,
  Target,
  Focus,
  Aperture,
  Camera as CameraIcon,
  CameraOff,
  Video as VideoIcon,
  VideoOff,
  Film,
  Image as ImageIcon,
  ImageOff,
  ImagePlus,
  ImageMinus,
  Images,
  PictureInPicture,
  PictureInPicture2,
  Maximize2 as Maximize2Icon,
  Minimize2 as Minimize2Icon,
  MoveDiagonal,
  MoveDiagonal2,
  MoveHorizontal,
  MoveVertical,
  ArrowLeftRight,
  ArrowUpDown,
  ArrowsUpFromLine,
  ArrowsDownFromLine,
  ArrowsLeftFromLine,
  ArrowsRightFromLine,
  ArrowsUpDown,
  ArrowsLeftRight,
  Expand,
  Shrink,
  Maximize as MaximizeIcon,
  Minimize as MinimizeIcon,
  PanelTop,
  PanelBottom,
  PanelLeftClose,
  PanelRightClose,
  PanelTopClose,
  PanelBottomClose,
  Columns2,
  Columns3,
  Columns4,
  Rows2,
  Rows3,
  Rows4,
  Grid2x2,
  Grid3x3,
  Grid4x4,
  LayoutTemplate,
  LayoutDashboard,
  LayoutPanelLeft,
  LayoutPanelTop,
  LayoutGrid as LayoutGridIcon,
  LayoutList as LayoutListIcon,
  AppWindow,
  AppWindowMac,
  Browser,
  Window,
  PanelsTopLeft,
  SidebarClose,
  SidebarOpen,
  PanelLeftInactive,
  PanelRightInactive,
  PanelTopInactive,
  PanelBottomInactive,
  SquareStack,
  SquareKanban,
  SquareDashed,
  SquareDot,
  SquareEqual,
  SquareSlash,
  SquareAsterisk,
  SquareCode,
  SquareFunction,
  SquareLibrary,
  SquareM,
  SquareMenu,
  SquareMinus,
  SquareMoreHorizontal,
  SquareMoreVertical,
  SquareMousePointer,
  SquareParking,
  SquareParkingOff,
  SquarePen,
  SquarePercent,
  SquarePhone,
  SquarePi,
  SquarePilcrow,
  SquarePlay,
  SquarePlus,
  SquarePower,
  SquareRadical,
  SquareScissors,
  SquareSigma,
  SquareSplitHorizontal,
  SquareSplitVertical,
  SquareSquare,
  SquareStack as SquareStackIcon,
  SquareTerminal,
  SquareUser,
  SquareUserRound,
  SquareX,
  CircleDot,
  CircleDashed,
  CircleEqual,
  CircleSlash,
  CircleSlash2,
  CircleEllipsis,
  CircleFadingPlus,
  CircleGauge,
  CircleHelp,
  CircleMinus,
  CircleOff,
  CircleParking,
  CircleParkingOff,
  CirclePause,
  CirclePercent,
  CirclePlay,
  CirclePlus,
  CirclePower,
  CircleSlash as CircleSlashIcon,
  CircleStop,
  CircleUser,
  CircleUserRound,
  CircleX,
  CircleCheck,
  CircleCheckBig,
  CircleAlert,
  CircleArrowDown,
  CircleArrowLeft,
  CircleArrowRight,
  CircleArrowUp,
  CircleArrowUpLeft,
  CircleArrowUpRight,
  CircleArrowDownLeft,
  CircleArrowDownRight,
  CircleChevronDown,
  CircleChevronLeft,
  CircleChevronRight,
  CircleChevronUp,
  CircleDotDashed,
  CircleDollarSign,
  CircleDot as CircleDotIcon,
  OctagonAlert,
  OctagonPause,
  OctagonX,
  TriangleAlert,
  TriangleRight,
  TriangleLeft,
  Hexagon as HexagonIcon,
  Pentagon as PentagonIcon,
  Octagon as OctagonIcon,
  Star as StarIcon2,
  Sparkle,
  Sparkles as SparklesIcon,
  Zap as ZapIcon,
  ZapOff,
  Flame,
  FlameKindling,
  Thermometer,
  ThermometerSnowflake,
  ThermometerSun,
  Droplet,
  Droplets,
  DropletOff,
  Cloud as CloudIcon,
  CloudRain,
  CloudSnow,
  CloudLightning,
  CloudFog,
  CloudSun,
  CloudMoon,
  CloudOff,
  CloudDownload,
  CloudUpload,
  CloudCog,
  CloudDrizzle,
  CloudHail,
  CloudRainWind,
  CloudLightning as CloudLightningIcon,
  CloudSunRain,
  CloudMoonRain,
  CloudSnow as CloudSnowIcon,
  CloudFog as CloudFogIcon,
  Sun as SunIcon,
  SunDim,
  SunMedium,
  SunMoon,
  Moon as MoonIcon,
  MoonStar,
  Stars,
  Sunset,
  Sunrise,
  Sunset as SunsetIcon,
  Sunrise as SunriseIcon,
  Umbrella,
  UmbrellaOff,
  Wind,
  Snowflake,
  Tornado,
  Cloudy,
  CloudRain as CloudRainIcon,
  CloudDrizzle as CloudDrizzleIcon,
  CloudHail as CloudHailIcon,
  CloudRainWind as CloudRainWindIcon,
  CloudSunRain as CloudSunRainIcon,
  CloudMoonRain as CloudMoonRainIcon,
  CloudSnow as CloudSnowIcon2,
  CloudFog as CloudFogIcon2,
  CloudLightning as CloudLightningIcon2,
  CloudOff as CloudOffIcon,
  CloudDownload as CloudDownloadIcon,
  CloudUpload as CloudUploadIcon,
  CloudCog as CloudCogIcon,
  Database as DatabaseIcon,
  DatabaseBackup,
  DatabaseZap,
  Server as ServerIcon,
  ServerOff,
  ServerCog,
  ServerCrash,
  HardDrive,
  HardDriveDownload,
  HardDriveUpload,
  Cpu,
  MemoryStick,
  Disc,
  Disc3,
  DiscAlbum,
  Disc2,
  Disc3 as Disc3Icon,
  DiscAlbum as DiscAlbumIcon,
  Disc2 as Disc2Icon,
  Usb,
  Usb2,
  Usb3,
  Hdmi,
  Hdmi2,
  Hdmi3,
  Hdmi4,
  Hdmi5,
  Hdmi6,
  Hdmi7,
  Hdmi8,
  Hdmi9,
  Hdmi10,
  Hdmi11,
  Hdmi12,
  Hdmi13,
  Hdmi14,
  Hdmi15,
  Hdmi16,
  Hdmi17,
  Hdmi18,
  Hdmi19,
  Hdmi20,
  Hdmi21,
  Hdmi22,
  Hdmi23,
  Hdmi24,
  Hdmi25,
  Hdmi26,
  Hdmi27,
  Hdmi28,
  Hdmi29,
  Hdmi30,
  Hdmi31,
  Hdmi32,
  Hdmi33,
  Hdmi34,
  Hdmi35,
  Hdmi36,
  Hdmi37,
  Hdmi38,
  Hdmi39,
  Hdmi40,
  Hdmi41,
  Hdmi42,
  Hdmi43,
  Hdmi44,
  Hdmi45,
  Hdmi46,
  Hdmi47,
  Hdmi48,
  Hdmi49,
  Hdmi50,
  Hdmi51,
  Hdmi52,
  Hdmi53,
  Hdmi54,
  Hdmi55,
  Hdmi56,
  Hdmi57,
  Hdmi58,
  Hdmi59,
  Hdmi60,
  Hdmi61,
  Hdmi62,
  Hdmi63,
  Hdmi64,
  Hdmi65,
  Hdmi66,
  Hdmi67,
  Hdmi68,
  Hdmi69,
  Hdmi70,
  Hdmi71,
  Hdmi72,
  Hdmi73,
  Hdmi74,
  Hdmi75,
  Hdmi76,
  Hdmi77,
  Hdmi78,
  Hdmi79,
  Hdmi80,
  Hdmi81,
  Hdmi82,
  Hdmi83,
  Hdmi84,
  Hdmi85,
  Hdmi86,
  Hdmi87,
  Hdmi88,
  Hdmi89,
  Hdmi90,
  Hdmi91,
  Hdmi92,
  Hdmi93,
  Hdmi94,
  Hdmi95,
  Hdmi96,
  Hdmi97,
  Hdmi98,
  Hdmi99,
  Hdmi100,
  type LucideIcon,
} from "lucide-react";

export interface Tool {
  id: string;
  name: string;
  description: string;
  category: 'json' | 'web' | 'dev' | 'frontend' | 'productivity' | 'security' | 'converter' | 'generator';
  path: string;
  icon: LucideIcon;
  badge?: string;
  isNew?: boolean;
  isPopular?: boolean;
}

export const tools: Tool[] = [
  // JSON Tools
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    description: 'Format, validate, and beautify JSON data with syntax highlighting',
    category: 'json',
    path: '/json-formatter',
    icon: FileJson,
    isPopular: true,
  },
  {
    id: 'json-to-ts',
    name: 'JSON to TypeScript',
    description: 'Convert JSON to TypeScript interfaces automatically',
    category: 'json',
    path: '/json-to-ts',
    icon: Code2,
    isNew: true,
  },
  {
    id: 'json-to-csv',
    name: 'JSON to CSV',
    description: 'Convert JSON data to CSV format',
    category: 'json',
    path: '/json-to-csv',
    icon: Table,
  },
  {
    id: 'json-to-yaml',
    name: 'JSON to YAML',
    description: 'Convert JSON to YAML and vice versa',
    category: 'json',
    path: '/json-to-yaml',
    icon: FileCode,
  },
  {
    id: 'json-diff',
    name: 'JSON Diff',
    description: 'Compare two JSON objects and find differences',
    category: 'json',
    path: '/json-diff',
    icon: GitCompare,
    isNew: true,
  },
  
  // Web & API Tools
  {
    id: 'jwt-decoder',
    name: 'JWT Decoder',
    description: 'Decode and inspect JWT tokens with payload analysis',
    category: 'web',
    path: '/jwt-decoder',
    icon: Key,
    isPopular: true,
  },
  {
    id: 'base64',
    name: 'Base64 Encoder/Decoder',
    description: 'Encode and decode Base64 strings with Unicode support',
    category: 'web',
    path: '/base64',
    icon: Binary,
    isPopular: true,
  },
  {
    id: 'url-encoder',
    name: 'URL Encoder/Decoder',
    description: 'Encode and decode URL parameters and full URLs',
    category: 'web',
    path: '/url-encoder',
    icon: Globe,
  },
  {
    id: 'curl-converter',
    name: 'Curl Converter',
    description: 'Convert curl commands to fetch, axios, or other formats',
    category: 'web',
    path: '/curl-converter',
    icon: Terminal,
  },
  {
    id: 'html-encoder',
    name: 'HTML Encoder/Decoder',
    description: 'Encode and decode HTML entities',
    category: 'web',
    path: '/html-encoder',
    icon: Code,
    isNew: true,
  },
  {
    id: 'query-parser',
    name: 'Query String Parser',
    description: 'Parse and build URL query strings',
    category: 'web',
    path: '/query-parser',
    icon: Search,
  },
  
  // Dev Utilities
  {
    id: 'timestamp',
    name: 'Timestamp Converter',
    description: 'Convert between Unix timestamps and human-readable dates',
    category: 'dev',
    path: '/timestamp',
    icon: Clock,
    isPopular: true,
  },
  {
    id: 'regex-tester',
    name: 'Regex Tester',
    description: 'Test regular expressions with live matching and capture groups',
    category: 'dev',
    path: '/regex-tester',
    icon: Regex,
    isPopular: true,
  },
  {
    id: 'diff-checker',
    name: 'Diff Checker',
    description: 'Compare two texts and find differences with syntax highlighting',
    category: 'dev',
    path: '/diff-checker',
    icon: GitCompare,
  },
  {
    id: 'hash-generator',
    name: 'Hash Generator',
    description: 'Generate MD5, SHA1, SHA256, SHA512 hashes',
    category: 'dev',
    path: '/hash-generator',
    icon: Hash,
  },
  {
    id: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Generate random UUIDs/GUIDs with multiple formats',
    category: 'dev',
    path: '/uuid-generator',
